
server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지를 설정하는 속성.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

# mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Dserver.port=9003'
# java -jar -Dserver.port=9004 /target/user-service-0.0.1-SNAPSHOT.jar